const express = require('express')
const router = express.Router()
const animeController = require('../controllers/animeController')
router.get('/categories/:id',animeController.getAnimeByCategories)
router.get('/:id/character',animeController.getCharacterAnimeByIDAnime)
router.post('/:id/character',animeController.addCharacterAnimeToAnimeID)
router.put('/character/:id',animeController.updateCharacterAnimeByID)
router.delete('/character/:id',animeController.deleteCharacterAnimeByID)
router.put('/:id',animeController.updateAnimes)
router.delete('/:id',animeController.deleteAnimes)
router.get('/search/:search',animeController.getAnimeByName)
router.get('/:id',animeController.getAnimeByID)
router.post('/',animeController.AddAnimes)
router.get('/',animeController.getAllAnimes)
module.exports = router