const accountRoute = require('./accountRoute')
const filmRoute = require('./filmRoute')
const animeRoute = require('./animeRoute')
const comicRoute = require('./comicRoute')
const authorComicRouter = require('./authorComicRoute')
const authorFilmRouter = require('./authorFilmRoute')
const authorAnimeRouter = require('./authorAnimeRoute')
const filmItemRouter = require('./filmItemRoute')
const animeItemRouter = require('./animeItemRoute')
const loginRoute = require('./loginRoute')
const commentFilmRoute = require('./commentFilmRoute')
const commentAnimeRoute = require('./commentAnimeRoute')
const auth = require('./OAuth')
const uploadImageRoute = require('./uploadImageRoute')
const uploadVideoRoute = require('./uploadVideoRoute')
const categories = require('./categoryFilmRoute')
const categoriesAnime = require('./categoryAnimeRoute')
const  uploadImage = require('../middlewares/uploadImage')
const  uploadVideo = require('../middlewares/uploadVideo')
function router(app)
{
    app.use('/films',filmRoute)
    app.use('/animes',animeRoute)
    app.use('/animeitems',animeItemRouter)
    app.use('/comments',commentFilmRoute)
    app.use('/commentAnimes',commentAnimeRoute)
    app.use('/categoryFilms',categories)
    app.use('/categoryAnimes',categoriesAnime)
    app.use('/filmitems',filmItemRouter)
    app.use('/authors/comics',authorComicRouter)
    app.use('/authors/films',authorFilmRouter)
    app.use('/authors/animes',authorAnimeRouter)
    app.use('/comics',comicRoute)
    app.use('/accounts',accountRoute)
    app.use('/login',loginRoute)
    app.use('/authorization',auth)
    app.use('/uploadImages',uploadImage.any(),uploadImageRoute)
    app.use('/uploadVideos',uploadVideo.any(),uploadVideoRoute)
}   
module.exports = router